package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-51b54c9e59b63e0fb0abe04daff984b4fb85d07ef3fcb7973595bce215c10515 */
/* JADX INFO: loaded from: classes.dex */
public final class e8 {
    public int a;
    public final h8 b;
    public final g8 c;
    public final f8 d;
    public final i8 e;
    public HashMap f;

    public e8() {
        h8 h8Var = new h8();
        h8Var.a = 0;
        h8Var.b = 0;
        h8Var.c = 1.0f;
        h8Var.d = Float.NaN;
        this.b = h8Var;
        g8 g8Var = new g8();
        g8Var.a = -1;
        g8Var.b = 0;
        g8Var.c = -1;
        g8Var.d = Float.NaN;
        g8Var.e = Float.NaN;
        g8Var.f = Float.NaN;
        g8Var.g = -1;
        g8Var.h = null;
        g8Var.i = -1;
        this.c = g8Var;
        f8 f8Var = new f8();
        f8Var.a = false;
        f8Var.d = -1;
        f8Var.e = -1;
        f8Var.f = -1.0f;
        f8Var.g = true;
        f8Var.h = -1;
        f8Var.i = -1;
        f8Var.j = -1;
        f8Var.k = -1;
        f8Var.l = -1;
        f8Var.m = -1;
        f8Var.n = -1;
        f8Var.o = -1;
        f8Var.p = -1;
        f8Var.q = -1;
        f8Var.r = -1;
        f8Var.s = -1;
        f8Var.t = -1;
        f8Var.u = -1;
        f8Var.v = -1;
        f8Var.w = 0.5f;
        f8Var.x = 0.5f;
        f8Var.y = null;
        f8Var.z = -1;
        f8Var.A = 0;
        f8Var.B = 0.0f;
        f8Var.C = -1;
        f8Var.D = -1;
        f8Var.E = -1;
        f8Var.F = 0;
        f8Var.G = 0;
        f8Var.H = 0;
        f8Var.I = 0;
        f8Var.J = 0;
        f8Var.K = 0;
        f8Var.L = 0;
        f8Var.M = Integer.MIN_VALUE;
        f8Var.N = Integer.MIN_VALUE;
        f8Var.O = Integer.MIN_VALUE;
        f8Var.P = Integer.MIN_VALUE;
        f8Var.Q = Integer.MIN_VALUE;
        f8Var.R = Integer.MIN_VALUE;
        f8Var.S = Integer.MIN_VALUE;
        f8Var.T = -1.0f;
        f8Var.U = -1.0f;
        f8Var.V = 0;
        f8Var.W = 0;
        f8Var.X = 0;
        f8Var.Y = 0;
        f8Var.Z = 0;
        f8Var.a0 = 0;
        f8Var.b0 = 0;
        f8Var.c0 = 0;
        f8Var.d0 = 1.0f;
        f8Var.e0 = 1.0f;
        f8Var.f0 = -1;
        f8Var.g0 = 0;
        f8Var.h0 = -1;
        f8Var.l0 = false;
        f8Var.m0 = false;
        f8Var.n0 = true;
        f8Var.o0 = 0;
        this.d = f8Var;
        i8 i8Var = new i8();
        i8Var.a = 0.0f;
        i8Var.b = 0.0f;
        i8Var.c = 0.0f;
        i8Var.d = 1.0f;
        i8Var.e = 1.0f;
        i8Var.f = Float.NaN;
        i8Var.g = Float.NaN;
        i8Var.h = -1;
        i8Var.i = 0.0f;
        i8Var.j = 0.0f;
        i8Var.k = 0.0f;
        i8Var.l = false;
        i8Var.m = 0.0f;
        this.e = i8Var;
        this.f = new HashMap();
    }

    public final void a(z7 z7Var) {
        f8 f8Var = this.d;
        z7Var.e = f8Var.h;
        z7Var.f = f8Var.i;
        z7Var.g = f8Var.j;
        z7Var.h = f8Var.k;
        z7Var.i = f8Var.l;
        z7Var.j = f8Var.m;
        z7Var.k = f8Var.n;
        z7Var.l = f8Var.o;
        z7Var.m = f8Var.p;
        z7Var.n = f8Var.q;
        z7Var.o = f8Var.r;
        z7Var.s = f8Var.s;
        z7Var.t = f8Var.t;
        z7Var.u = f8Var.u;
        z7Var.v = f8Var.v;
        ((ViewGroup.MarginLayoutParams) z7Var).leftMargin = f8Var.F;
        ((ViewGroup.MarginLayoutParams) z7Var).rightMargin = f8Var.G;
        ((ViewGroup.MarginLayoutParams) z7Var).topMargin = f8Var.H;
        ((ViewGroup.MarginLayoutParams) z7Var).bottomMargin = f8Var.I;
        z7Var.A = f8Var.R;
        z7Var.B = f8Var.Q;
        z7Var.x = f8Var.N;
        z7Var.z = f8Var.P;
        z7Var.E = f8Var.w;
        z7Var.F = f8Var.x;
        z7Var.p = f8Var.z;
        z7Var.q = f8Var.A;
        z7Var.r = f8Var.B;
        z7Var.G = f8Var.y;
        z7Var.T = f8Var.C;
        z7Var.U = f8Var.D;
        z7Var.I = f8Var.T;
        z7Var.H = f8Var.U;
        z7Var.K = f8Var.W;
        z7Var.J = f8Var.V;
        z7Var.W = f8Var.l0;
        z7Var.X = f8Var.m0;
        z7Var.L = f8Var.X;
        z7Var.M = f8Var.Y;
        z7Var.P = f8Var.Z;
        z7Var.Q = f8Var.a0;
        z7Var.N = f8Var.b0;
        z7Var.O = f8Var.c0;
        z7Var.R = f8Var.d0;
        z7Var.S = f8Var.e0;
        z7Var.V = f8Var.E;
        z7Var.c = f8Var.f;
        z7Var.a = f8Var.d;
        z7Var.b = f8Var.e;
        ((ViewGroup.MarginLayoutParams) z7Var).width = f8Var.b;
        ((ViewGroup.MarginLayoutParams) z7Var).height = f8Var.c;
        String str = f8Var.k0;
        if (str != null) {
            z7Var.Y = str;
        }
        z7Var.Z = f8Var.o0;
        z7Var.setMarginStart(f8Var.K);
        z7Var.setMarginEnd(f8Var.J);
        z7Var.a();
    }

    public final Object clone() {
        e8 e8Var = new e8();
        f8 f8Var = e8Var.d;
        f8Var.getClass();
        f8 f8Var2 = this.d;
        f8Var.a = f8Var2.a;
        f8Var.b = f8Var2.b;
        f8Var.c = f8Var2.c;
        f8Var.d = f8Var2.d;
        f8Var.e = f8Var2.e;
        f8Var.f = f8Var2.f;
        f8Var.g = f8Var2.g;
        f8Var.h = f8Var2.h;
        f8Var.i = f8Var2.i;
        f8Var.j = f8Var2.j;
        f8Var.k = f8Var2.k;
        f8Var.l = f8Var2.l;
        f8Var.m = f8Var2.m;
        f8Var.n = f8Var2.n;
        f8Var.o = f8Var2.o;
        f8Var.p = f8Var2.p;
        f8Var.q = f8Var2.q;
        f8Var.r = f8Var2.r;
        f8Var.s = f8Var2.s;
        f8Var.t = f8Var2.t;
        f8Var.u = f8Var2.u;
        f8Var.v = f8Var2.v;
        f8Var.w = f8Var2.w;
        f8Var.x = f8Var2.x;
        f8Var.y = f8Var2.y;
        f8Var.z = f8Var2.z;
        f8Var.A = f8Var2.A;
        f8Var.B = f8Var2.B;
        f8Var.C = f8Var2.C;
        f8Var.D = f8Var2.D;
        f8Var.E = f8Var2.E;
        f8Var.F = f8Var2.F;
        f8Var.G = f8Var2.G;
        f8Var.H = f8Var2.H;
        f8Var.I = f8Var2.I;
        f8Var.J = f8Var2.J;
        f8Var.K = f8Var2.K;
        f8Var.L = f8Var2.L;
        f8Var.M = f8Var2.M;
        f8Var.N = f8Var2.N;
        f8Var.O = f8Var2.O;
        f8Var.P = f8Var2.P;
        f8Var.Q = f8Var2.Q;
        f8Var.R = f8Var2.R;
        f8Var.S = f8Var2.S;
        f8Var.T = f8Var2.T;
        f8Var.U = f8Var2.U;
        f8Var.V = f8Var2.V;
        f8Var.W = f8Var2.W;
        f8Var.X = f8Var2.X;
        f8Var.Y = f8Var2.Y;
        f8Var.Z = f8Var2.Z;
        f8Var.a0 = f8Var2.a0;
        f8Var.b0 = f8Var2.b0;
        f8Var.c0 = f8Var2.c0;
        f8Var.d0 = f8Var2.d0;
        f8Var.e0 = f8Var2.e0;
        f8Var.f0 = f8Var2.f0;
        f8Var.g0 = f8Var2.g0;
        f8Var.h0 = f8Var2.h0;
        f8Var.k0 = f8Var2.k0;
        int[] iArr = f8Var2.i0;
        if (iArr == null || f8Var2.j0 != null) {
            f8Var.i0 = null;
        } else {
            f8Var.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        f8Var.j0 = f8Var2.j0;
        f8Var.l0 = f8Var2.l0;
        f8Var.m0 = f8Var2.m0;
        f8Var.n0 = f8Var2.n0;
        f8Var.o0 = f8Var2.o0;
        g8 g8Var = e8Var.c;
        g8Var.getClass();
        g8 g8Var2 = this.c;
        g8Var2.getClass();
        g8Var.a = g8Var2.a;
        g8Var.c = g8Var2.c;
        g8Var.e = g8Var2.e;
        g8Var.d = g8Var2.d;
        h8 h8Var = this.b;
        int i = h8Var.a;
        h8 h8Var2 = e8Var.b;
        h8Var2.a = i;
        h8Var2.c = h8Var.c;
        h8Var2.d = h8Var.d;
        h8Var2.b = h8Var.b;
        i8 i8Var = e8Var.e;
        i8Var.getClass();
        i8 i8Var2 = this.e;
        i8Var2.getClass();
        i8Var.a = i8Var2.a;
        i8Var.b = i8Var2.b;
        i8Var.c = i8Var2.c;
        i8Var.d = i8Var2.d;
        i8Var.e = i8Var2.e;
        i8Var.f = i8Var2.f;
        i8Var.g = i8Var2.g;
        i8Var.h = i8Var2.h;
        i8Var.i = i8Var2.i;
        i8Var.j = i8Var2.j;
        i8Var.k = i8Var2.k;
        i8Var.l = i8Var2.l;
        i8Var.m = i8Var2.m;
        e8Var.a = this.a;
        return e8Var;
    }
}
